//
// auto-generated by ops.py
//
#include "./MPI_inline/opensbli_common.h"


void ops_init_backend() {}

//user kernel files
#include "opensbliblock00Kernel032_mpiinline_kernel.cpp"
#include "opensbliblock00Kernel026_mpiinline_kernel.cpp"
#include "opensbliblock00Kernel027_mpiinline_kernel.cpp"
#include "opensbliblock00Kernel028_mpiinline_kernel.cpp"
#include "opensbliblock00Kernel029_mpiinline_kernel.cpp"
#include "opensbliblock00Kernel030_mpiinline_kernel.cpp"
#include "opensbliblock00Kernel031_mpiinline_kernel.cpp"
#include "opensbliblock00Kernel033_mpiinline_kernel.cpp"
#include "opensbliblock00Kernel001_mpiinline_kernel.cpp"
#include "opensbliblock00Kernel005_mpiinline_kernel.cpp"
#include "opensbliblock00Kernel009_mpiinline_kernel.cpp"
#include "opensbliblock00Kernel017_mpiinline_kernel.cpp"
#include "opensbliblock00Kernel018_mpiinline_kernel.cpp"
#include "opensbliblock00Kernel000_mpiinline_kernel.cpp"
#include "opensbliblock00Kernel002_mpiinline_kernel.cpp"
#include "opensbliblock00Kernel003_mpiinline_kernel.cpp"
#include "opensbliblock00Kernel004_mpiinline_kernel.cpp"
#include "opensbliblock00Kernel006_mpiinline_kernel.cpp"
#include "opensbliblock00Kernel007_mpiinline_kernel.cpp"
#include "opensbliblock00Kernel008_mpiinline_kernel.cpp"
#include "opensbliblock00Kernel010_mpiinline_kernel.cpp"
#include "opensbliblock00Kernel011_mpiinline_kernel.cpp"
#include "opensbliblock00Kernel024_mpiinline_kernel.cpp"
#include "opensbliblock00Kernel025_mpiinline_kernel.cpp"
#include "opensbliblock00Kernel035_mpiinline_kernel.cpp"
#include "opensbliblock00Kernel034_mpiinline_kernel.cpp"
