//
// auto-generated by ops.py
//

#define OPS_GPU

int xdim2_final_update_kernel;
int ydim2_final_update_kernel;
int zdim2_final_update_kernel;
int xdim3_final_update_kernel;
int ydim3_final_update_kernel;
int zdim3_final_update_kernel;
int xdim4_final_update_kernel;
int ydim4_final_update_kernel;
int zdim4_final_update_kernel;
int xdim5_final_update_kernel;
int ydim5_final_update_kernel;
int zdim5_final_update_kernel;
int xdim6_final_update_kernel;
int ydim6_final_update_kernel;
int zdim6_final_update_kernel;

//user function
inline 
void final_update_kernel(const int *idx,
  const float *dt,
  const ptrm_float  k1,
  const ptrm_float  k2,
  const ptrm_float  k3,
  ptrm_float  k4,
  ptrm_float  yy)
{
  for (int i = 0; i<6; i++) {

    OPS_ACC(k4, i,0,0,0) = OPS_ACC(k4, i,0,0,0)* *dt;

    OPS_ACC(yy, i,0,0,0) = OPS_ACC(yy, i,0,0,0) +
      OPS_ACC(k1, i,0,0,0)/6.f +
      OPS_ACC(k2, i,0,0,0)/3.f +
      OPS_ACC(k3, i,0,0,0)/3.f +
      OPS_ACC(k4, i,0,0,0)/6.f;

  }
}


void final_update_kernel_c_wrapper(
  int *p_a0,
  float p_a1,
  float *p_a2,
  float *p_a3,
  float *p_a4,
  float *p_a5,
  float *p_a6,
  int arg_idx0, int arg_idx1, int arg_idx2,
  int x_size, int y_size, int z_size) {
  #ifdef OPS_GPU
  #pragma acc parallel deviceptr(p_a2,p_a3,p_a4,p_a5,p_a6)
  #pragma acc loop
  #endif
  for ( int n_z=0; n_z<z_size; n_z++ ){
    #ifdef OPS_GPU
    #pragma acc loop
    #endif
    for ( int n_y=0; n_y<y_size; n_y++ ){
      #ifdef OPS_GPU
      #pragma acc loop
      #endif
      for ( int n_x=0; n_x<x_size; n_x++ ){
        int arg_idx[] = {arg_idx0+n_x, arg_idx1+n_y, arg_idx2+n_z};
        #ifdef OPS_SOA
        const ptrm_float ptr2 = {  p_a2 + n_x*1 + n_y*xdim2_final_update_kernel*1 + n_z*xdim2_final_update_kernel*ydim2_final_update_kernel*1, xdim2_final_update_kernel, ydim2_final_update_kernel, zdim2_final_update_kernel};
        #else
        const ptrm_float ptr2 = {  p_a2 + n_x*1 + n_y*xdim2_final_update_kernel*1 + n_z*xdim2_final_update_kernel*ydim2_final_update_kernel*1, xdim2_final_update_kernel, ydim2_final_update_kernel, 6};
        #endif
        #ifdef OPS_SOA
        const ptrm_float ptr3 = {  p_a3 + n_x*1 + n_y*xdim3_final_update_kernel*1 + n_z*xdim3_final_update_kernel*ydim3_final_update_kernel*1, xdim3_final_update_kernel, ydim3_final_update_kernel, zdim3_final_update_kernel};
        #else
        const ptrm_float ptr3 = {  p_a3 + n_x*1 + n_y*xdim3_final_update_kernel*1 + n_z*xdim3_final_update_kernel*ydim3_final_update_kernel*1, xdim3_final_update_kernel, ydim3_final_update_kernel, 6};
        #endif
        #ifdef OPS_SOA
        const ptrm_float ptr4 = {  p_a4 + n_x*1 + n_y*xdim4_final_update_kernel*1 + n_z*xdim4_final_update_kernel*ydim4_final_update_kernel*1, xdim4_final_update_kernel, ydim4_final_update_kernel, zdim4_final_update_kernel};
        #else
        const ptrm_float ptr4 = {  p_a4 + n_x*1 + n_y*xdim4_final_update_kernel*1 + n_z*xdim4_final_update_kernel*ydim4_final_update_kernel*1, xdim4_final_update_kernel, ydim4_final_update_kernel, 6};
        #endif
        #ifdef OPS_SOA
        ptrm_float ptr5 = {  p_a5 + n_x*1 + n_y*xdim5_final_update_kernel*1 + n_z*xdim5_final_update_kernel*ydim5_final_update_kernel*1, xdim5_final_update_kernel, ydim5_final_update_kernel, zdim5_final_update_kernel};
        #else
        ptrm_float ptr5 = {  p_a5 + n_x*1 + n_y*xdim5_final_update_kernel*1 + n_z*xdim5_final_update_kernel*ydim5_final_update_kernel*1, xdim5_final_update_kernel, ydim5_final_update_kernel, 6};
        #endif
        #ifdef OPS_SOA
        ptrm_float ptr6 = {  p_a6 + n_x*1 + n_y*xdim6_final_update_kernel*1 + n_z*xdim6_final_update_kernel*ydim6_final_update_kernel*1, xdim6_final_update_kernel, ydim6_final_update_kernel, zdim6_final_update_kernel};
        #else
        ptrm_float ptr6 = {  p_a6 + n_x*1 + n_y*xdim6_final_update_kernel*1 + n_z*xdim6_final_update_kernel*ydim6_final_update_kernel*1, xdim6_final_update_kernel, ydim6_final_update_kernel, 6};
        #endif
        final_update_kernel( arg_idx,
           &p_a1,
          ptr2,
          ptr3,
          ptr4,
          ptr5,
          ptr6 );

      }
    }
  }
}
