
include $(OPS_INSTALL_PATH)/../makefiles/Makefile.common
include $(OPS_INSTALL_PATH)/../makefiles/Makefile.mpi
include $(OPS_INSTALL_PATH)/../makefiles/Makefile.cuda

HEADERS=wave-propagation-kernels.h

OPS_FILES=wave-propagation.cpp

OPS_GENERATED=wave-propagation_ops.cpp

APP=wave-propagation
MAIN_SRC=wave-propagation

include $(OPS_INSTALL_PATH)/../makefiles/Makefile.c_app
