//
// auto-generated by ops.py
//

#define OPS_GPU

int xdim0_opensbliblock00Kernel025;
int ydim0_opensbliblock00Kernel025;
int xdim1_opensbliblock00Kernel025;
int ydim1_opensbliblock00Kernel025;
int xdim2_opensbliblock00Kernel025;
int ydim2_opensbliblock00Kernel025;
int xdim3_opensbliblock00Kernel025;
int ydim3_opensbliblock00Kernel025;
int xdim4_opensbliblock00Kernel025;
int ydim4_opensbliblock00Kernel025;
int xdim5_opensbliblock00Kernel025;
int ydim5_opensbliblock00Kernel025;
int xdim6_opensbliblock00Kernel025;
int ydim6_opensbliblock00Kernel025;
int xdim7_opensbliblock00Kernel025;
int ydim7_opensbliblock00Kernel025;
int xdim8_opensbliblock00Kernel025;
int ydim8_opensbliblock00Kernel025;
int xdim9_opensbliblock00Kernel025;
int ydim9_opensbliblock00Kernel025;
int xdim10_opensbliblock00Kernel025;
int ydim10_opensbliblock00Kernel025;
int xdim11_opensbliblock00Kernel025;
int ydim11_opensbliblock00Kernel025;
int xdim12_opensbliblock00Kernel025;
int ydim12_opensbliblock00Kernel025;
int xdim13_opensbliblock00Kernel025;
int ydim13_opensbliblock00Kernel025;
int xdim14_opensbliblock00Kernel025;
int ydim14_opensbliblock00Kernel025;
int xdim15_opensbliblock00Kernel025;
int ydim15_opensbliblock00Kernel025;
int xdim16_opensbliblock00Kernel025;
int ydim16_opensbliblock00Kernel025;

//user function
inline 
 void opensbliblock00Kernel025(const ptr_double wk8_B0,
  const ptr_double wk3_B0,
  const ptr_double wk2_B0,
  const ptr_double u0_B0,
  const ptr_double wk1_B0,
  const ptr_double u1_B0,
  const ptr_double wk4_B0,
  const ptr_double wk7_B0,
  const ptr_double T_B0,
  const ptr_double u2_B0,
  const ptr_double wk5_B0,
  const ptr_double wk0_B0,
  const ptr_double wk6_B0,
  ptr_double Residual4_B0,
  ptr_double Residual1_B0,
  ptr_double Residual3_B0,
  ptr_double Residual2_B0)
{
   double localeval_16 = 0.0;
   double localeval_5 = 0.0;
   double localeval_9 = 0.0;
   double localeval_7 = 0.0;
   double localeval_6 = 0.0;
   double localeval_15 = 0.0;
   double localeval_3 = 0.0;
   double localeval_2 = 0.0;
   double localeval_14 = 0.0;
   double localeval_10 = 0.0;
   double localeval_0 = 0.0;
   double localeval_1 = 0.0;
   double localeval_4 = 0.0;
   double localeval_8 = 0.0;
   double localeval_11 = 0.0;
   double localeval_12 = 0.0;
   double localeval_13 = 0.0;
   double localeval_17 = 0.0;
    localeval_0 = (rc7)*inv_3*(16*OPS_ACC(T_B0, 1,0,0) - 30*OPS_ACC(T_B0, 0,0,0) - OPS_ACC(T_B0, 2,0,0) -
      OPS_ACC(T_B0, -2,0,0) + 16*OPS_ACC(T_B0, -1,0,0));

    localeval_1 = (rc7)*inv_4*(16*OPS_ACC(T_B0, 0,1,0) - 30*OPS_ACC(T_B0, 0,0,0) - OPS_ACC(T_B0, 0,-2,0) -
      OPS_ACC(T_B0, 0,2,0) + 16*OPS_ACC(T_B0, 0,-1,0));

    localeval_2 = (rc7)*inv_5*(-OPS_ACC(T_B0, 0,0,-2) + 16*OPS_ACC(T_B0, 0,0,-1) - 30*OPS_ACC(T_B0, 0,0,0) -
      OPS_ACC(T_B0, 0,0,2) + 16*OPS_ACC(T_B0, 0,0,1));

    localeval_3 = (rc7)*inv_4*(-OPS_ACC(u0_B0, 0,2,0) + 16*OPS_ACC(u0_B0, 0,1,0) - 30*OPS_ACC(u0_B0, 0,0,0) +
      16*OPS_ACC(u0_B0, 0,-1,0) - OPS_ACC(u0_B0, 0,-2,0));

    localeval_4 = (rc7)*inv_5*(16*OPS_ACC(u0_B0, 0,0,1) - 30*OPS_ACC(u0_B0, 0,0,0) + 16*OPS_ACC(u0_B0, 0,0,-1) -
      OPS_ACC(u0_B0, 0,0,-2) - OPS_ACC(u0_B0, 0,0,2));

    localeval_5 = (rc7)*inv_3*(-OPS_ACC(u0_B0, 2,0,0) + 16*OPS_ACC(u0_B0, 1,0,0) - 30*OPS_ACC(u0_B0, 0,0,0) +
      16*OPS_ACC(u0_B0, -1,0,0) - OPS_ACC(u0_B0, -2,0,0));

    localeval_6 = (rc7)*inv_4*(16*OPS_ACC(u1_B0, 0,1,0) - OPS_ACC(u1_B0, 0,2,0) - OPS_ACC(u1_B0, 0,-2,0) +
      16*OPS_ACC(u1_B0, 0,-1,0) - 30*OPS_ACC(u1_B0, 0,0,0));

    localeval_7 = (rc7)*inv_3*(16*OPS_ACC(u1_B0, 1,0,0) - OPS_ACC(u1_B0, 2,0,0) - OPS_ACC(u1_B0, -2,0,0) +
      16*OPS_ACC(u1_B0, -1,0,0) - 30*OPS_ACC(u1_B0, 0,0,0));

    localeval_8 = (rc7)*inv_5*(16*OPS_ACC(u1_B0, 0,0,1) - OPS_ACC(u1_B0, 0,0,2) - OPS_ACC(u1_B0, 0,0,-2) +
      16*OPS_ACC(u1_B0, 0,0,-1) - 30*OPS_ACC(u1_B0, 0,0,0));

    localeval_9 = (rc7)*inv_5*(-OPS_ACC(u2_B0, 0,0,2) + 16*OPS_ACC(u2_B0, 0,0,-1) - OPS_ACC(u2_B0, 0,0,-2) -
      30*OPS_ACC(u2_B0, 0,0,0) + 16*OPS_ACC(u2_B0, 0,0,1));

    localeval_10 = (rc7)*inv_3*(16*OPS_ACC(u2_B0, -1,0,0) - OPS_ACC(u2_B0, -2,0,0) - 30*OPS_ACC(u2_B0, 0,0,0) +
      16*OPS_ACC(u2_B0, 1,0,0) - OPS_ACC(u2_B0, 2,0,0));

    localeval_11 = (rc7)*inv_4*(16*OPS_ACC(u2_B0, 0,-1,0) - OPS_ACC(u2_B0, 0,-2,0) - 30*OPS_ACC(u2_B0, 0,0,0) +
      16*OPS_ACC(u2_B0, 0,1,0) - OPS_ACC(u2_B0, 0,2,0));

    localeval_12 = (rc7)*inv_2*(-OPS_ACC(wk0_B0, 0,2,0) + OPS_ACC(wk0_B0, 0,-2,0) - 8*OPS_ACC(wk0_B0, 0,-1,0) +
      8*OPS_ACC(wk0_B0, 0,1,0));

    localeval_13 = (rc7)*inv_1*(OPS_ACC(wk0_B0, 0,0,-2) - OPS_ACC(wk0_B0, 0,0,2) + 8*OPS_ACC(wk0_B0, 0,0,1) -
      8*OPS_ACC(wk0_B0, 0,0,-1));

    localeval_14 = (rc7)*inv_2*(-OPS_ACC(wk3_B0, 0,2,0) + OPS_ACC(wk3_B0, 0,-2,0) + 8*OPS_ACC(wk3_B0, 0,1,0) -
      8*OPS_ACC(wk3_B0, 0,-1,0));

    localeval_15 = (rc7)*inv_1*(8*OPS_ACC(wk5_B0, 0,0,1) - OPS_ACC(wk5_B0, 0,0,2) + OPS_ACC(wk5_B0, 0,0,-2) -
      8*OPS_ACC(wk5_B0, 0,0,-1));

    localeval_16 = (rc7)*inv_1*(-8*OPS_ACC(wk6_B0, 0,0,-1) - OPS_ACC(wk6_B0, 0,0,2) + OPS_ACC(wk6_B0, 0,0,-2) +
      8*OPS_ACC(wk6_B0, 0,0,1));

    localeval_17 = (rc7)*inv_1*(-OPS_ACC(wk8_B0, 0,0,2) + 8*OPS_ACC(wk8_B0, 0,0,1) - 8*OPS_ACC(wk8_B0, 0,0,-1) +
      OPS_ACC(wk8_B0, 0,0,-2));

    OPS_ACC(Residual1_B0, 0,0,0) = 1.0*rcinv8*((rc9)*localeval_14 + (rc9)*localeval_16 + localeval_3 + localeval_4 +
      (rc10)*localeval_5) + OPS_ACC(Residual1_B0, 0,0,0);

    OPS_ACC(Residual2_B0, 0,0,0) = 1.0*rcinv8*((rc9)*localeval_12 + (rc9)*localeval_17 + (rc10)*localeval_6 +
      localeval_7 + localeval_8) + OPS_ACC(Residual2_B0, 0,0,0);

    OPS_ACC(Residual3_B0, 0,0,0) = 1.0*rcinv8*(localeval_10 + localeval_11 + (rc9)*localeval_13 + (rc9)*localeval_15 +
      (rc10)*localeval_9) + OPS_ACC(Residual3_B0, 0,0,0);

    OPS_ACC(Residual4_B0, 0,0,0) = 1.0*rcinv11*rcinv12*rcinv13*rcinv8*(localeval_0 + localeval_1 + localeval_2) +
      1.0*rcinv8*(OPS_ACC(wk1_B0, 0,0,0) + OPS_ACC(wk6_B0, 0,0,0))*OPS_ACC(wk1_B0, 0,0,0) +
      1.0*rcinv8*(OPS_ACC(wk1_B0, 0,0,0) + OPS_ACC(wk6_B0, 0,0,0))*OPS_ACC(wk6_B0, 0,0,0) +
      1.0*rcinv8*(OPS_ACC(wk2_B0, 0,0,0) + OPS_ACC(wk3_B0, 0,0,0))*OPS_ACC(wk2_B0, 0,0,0) +
      1.0*rcinv8*(OPS_ACC(wk2_B0, 0,0,0) + OPS_ACC(wk3_B0, 0,0,0))*OPS_ACC(wk3_B0, 0,0,0) +
      1.0*rcinv8*(OPS_ACC(wk4_B0, 0,0,0) + OPS_ACC(wk8_B0, 0,0,0))*OPS_ACC(wk4_B0, 0,0,0) +
      1.0*rcinv8*(OPS_ACC(wk4_B0, 0,0,0) + OPS_ACC(wk8_B0, 0,0,0))*OPS_ACC(wk8_B0, 0,0,0) +
      1.0*rcinv8*(-rc14*OPS_ACC(wk0_B0, 0,0,0) - rc14*OPS_ACC(wk5_B0, 0,0,0) +
      (rc10)*OPS_ACC(wk7_B0, 0,0,0))*OPS_ACC(wk7_B0, 0,0,0) + 1.0*rcinv8*(-rc14*OPS_ACC(wk0_B0, 0,0,0) +
      (rc10)*OPS_ACC(wk5_B0, 0,0,0) - rc14*OPS_ACC(wk7_B0, 0,0,0))*OPS_ACC(wk5_B0, 0,0,0) +
      1.0*rcinv8*((rc10)*OPS_ACC(wk0_B0, 0,0,0) - rc14*OPS_ACC(wk5_B0, 0,0,0) -
      rc14*OPS_ACC(wk7_B0, 0,0,0))*OPS_ACC(wk0_B0, 0,0,0) + 1.0*rcinv8*(localeval_10 + localeval_11 +
      (rc9)*localeval_13 + (rc9)*localeval_15 + (rc10)*localeval_9)*OPS_ACC(u2_B0, 0,0,0) +
      1.0*rcinv8*((rc9)*localeval_12 + (rc9)*localeval_17 + (rc10)*localeval_6 + localeval_7 +
      localeval_8)*OPS_ACC(u1_B0, 0,0,0) + 1.0*rcinv8*((rc9)*localeval_14 + (rc9)*localeval_16 + localeval_3 +
      localeval_4 + (rc10)*localeval_5)*OPS_ACC(u0_B0, 0,0,0) + OPS_ACC(Residual4_B0, 0,0,0);

}


void opensbliblock00Kernel025_c_wrapper(
  double *p_a0,
  double *p_a1,
  double *p_a2,
  double *p_a3,
  double *p_a4,
  double *p_a5,
  double *p_a6,
  double *p_a7,
  double *p_a8,
  double *p_a9,
  double *p_a10,
  double *p_a11,
  double *p_a12,
  double *p_a13,
  double *p_a14,
  double *p_a15,
  double *p_a16,
  int x_size, int y_size, int z_size) {
  #ifdef OPS_GPU
  #pragma acc parallel deviceptr(p_a0,p_a1,p_a2,p_a3,p_a4,p_a5,p_a6,p_a7,p_a8,p_a9,p_a10,p_a11,p_a12,p_a13,p_a14,p_a15,p_a16)
  #pragma acc loop
  #endif
  for ( int n_z=0; n_z<z_size; n_z++ ){
    #ifdef OPS_GPU
    #pragma acc loop
    #endif
    for ( int n_y=0; n_y<y_size; n_y++ ){
      #ifdef OPS_GPU
      #pragma acc loop
      #endif
      for ( int n_x=0; n_x<x_size; n_x++ ){
        const ptr_double ptr0 = {  p_a0 + n_x*1*1 + n_y*xdim0_opensbliblock00Kernel025*1*1 + n_z*xdim0_opensbliblock00Kernel025*ydim0_opensbliblock00Kernel025*1*1, xdim0_opensbliblock00Kernel025, ydim0_opensbliblock00Kernel025};
        const ptr_double ptr1 = {  p_a1 + n_x*1*1 + n_y*xdim1_opensbliblock00Kernel025*1*1 + n_z*xdim1_opensbliblock00Kernel025*ydim1_opensbliblock00Kernel025*1*1, xdim1_opensbliblock00Kernel025, ydim1_opensbliblock00Kernel025};
        const ptr_double ptr2 = {  p_a2 + n_x*1*1 + n_y*xdim2_opensbliblock00Kernel025*1*1 + n_z*xdim2_opensbliblock00Kernel025*ydim2_opensbliblock00Kernel025*1*1, xdim2_opensbliblock00Kernel025, ydim2_opensbliblock00Kernel025};
        const ptr_double ptr3 = {  p_a3 + n_x*1*1 + n_y*xdim3_opensbliblock00Kernel025*1*1 + n_z*xdim3_opensbliblock00Kernel025*ydim3_opensbliblock00Kernel025*1*1, xdim3_opensbliblock00Kernel025, ydim3_opensbliblock00Kernel025};
        const ptr_double ptr4 = {  p_a4 + n_x*1*1 + n_y*xdim4_opensbliblock00Kernel025*1*1 + n_z*xdim4_opensbliblock00Kernel025*ydim4_opensbliblock00Kernel025*1*1, xdim4_opensbliblock00Kernel025, ydim4_opensbliblock00Kernel025};
        const ptr_double ptr5 = {  p_a5 + n_x*1*1 + n_y*xdim5_opensbliblock00Kernel025*1*1 + n_z*xdim5_opensbliblock00Kernel025*ydim5_opensbliblock00Kernel025*1*1, xdim5_opensbliblock00Kernel025, ydim5_opensbliblock00Kernel025};
        const ptr_double ptr6 = {  p_a6 + n_x*1*1 + n_y*xdim6_opensbliblock00Kernel025*1*1 + n_z*xdim6_opensbliblock00Kernel025*ydim6_opensbliblock00Kernel025*1*1, xdim6_opensbliblock00Kernel025, ydim6_opensbliblock00Kernel025};
        const ptr_double ptr7 = {  p_a7 + n_x*1*1 + n_y*xdim7_opensbliblock00Kernel025*1*1 + n_z*xdim7_opensbliblock00Kernel025*ydim7_opensbliblock00Kernel025*1*1, xdim7_opensbliblock00Kernel025, ydim7_opensbliblock00Kernel025};
        const ptr_double ptr8 = {  p_a8 + n_x*1*1 + n_y*xdim8_opensbliblock00Kernel025*1*1 + n_z*xdim8_opensbliblock00Kernel025*ydim8_opensbliblock00Kernel025*1*1, xdim8_opensbliblock00Kernel025, ydim8_opensbliblock00Kernel025};
        const ptr_double ptr9 = {  p_a9 + n_x*1*1 + n_y*xdim9_opensbliblock00Kernel025*1*1 + n_z*xdim9_opensbliblock00Kernel025*ydim9_opensbliblock00Kernel025*1*1, xdim9_opensbliblock00Kernel025, ydim9_opensbliblock00Kernel025};
        const ptr_double ptr10 = {  p_a10 + n_x*1*1 + n_y*xdim10_opensbliblock00Kernel025*1*1 + n_z*xdim10_opensbliblock00Kernel025*ydim10_opensbliblock00Kernel025*1*1, xdim10_opensbliblock00Kernel025, ydim10_opensbliblock00Kernel025};
        const ptr_double ptr11 = {  p_a11 + n_x*1*1 + n_y*xdim11_opensbliblock00Kernel025*1*1 + n_z*xdim11_opensbliblock00Kernel025*ydim11_opensbliblock00Kernel025*1*1, xdim11_opensbliblock00Kernel025, ydim11_opensbliblock00Kernel025};
        const ptr_double ptr12 = {  p_a12 + n_x*1*1 + n_y*xdim12_opensbliblock00Kernel025*1*1 + n_z*xdim12_opensbliblock00Kernel025*ydim12_opensbliblock00Kernel025*1*1, xdim12_opensbliblock00Kernel025, ydim12_opensbliblock00Kernel025};
        ptr_double ptr13 = {  p_a13 + n_x*1*1 + n_y*xdim13_opensbliblock00Kernel025*1*1 + n_z*xdim13_opensbliblock00Kernel025*ydim13_opensbliblock00Kernel025*1*1, xdim13_opensbliblock00Kernel025, ydim13_opensbliblock00Kernel025};
        ptr_double ptr14 = {  p_a14 + n_x*1*1 + n_y*xdim14_opensbliblock00Kernel025*1*1 + n_z*xdim14_opensbliblock00Kernel025*ydim14_opensbliblock00Kernel025*1*1, xdim14_opensbliblock00Kernel025, ydim14_opensbliblock00Kernel025};
        ptr_double ptr15 = {  p_a15 + n_x*1*1 + n_y*xdim15_opensbliblock00Kernel025*1*1 + n_z*xdim15_opensbliblock00Kernel025*ydim15_opensbliblock00Kernel025*1*1, xdim15_opensbliblock00Kernel025, ydim15_opensbliblock00Kernel025};
        ptr_double ptr16 = {  p_a16 + n_x*1*1 + n_y*xdim16_opensbliblock00Kernel025*1*1 + n_z*xdim16_opensbliblock00Kernel025*ydim16_opensbliblock00Kernel025*1*1, xdim16_opensbliblock00Kernel025, ydim16_opensbliblock00Kernel025};
        opensbliblock00Kernel025( ptr0, ptr1, ptr2, ptr3,
           ptr4, ptr5, ptr6, ptr7,
           ptr8, ptr9, ptr10, ptr11,
           ptr12, ptr13, ptr14, ptr15,
           ptr16);
      }
    }
  }
}
