//
// auto-generated by ops.py
//

int xdim0_opensbliblock00Kernel016;
int ydim0_opensbliblock00Kernel016;
int xdim1_opensbliblock00Kernel016;
int ydim1_opensbliblock00Kernel016;


//user function



void opensbliblock00Kernel016_c_wrapper(
  double * restrict wk42_B0_p,
  double * restrict wk9_B0_p,
  int x_size, int y_size, int z_size) {
  #pragma omp parallel for
  for ( int n_z=0; n_z<z_size; n_z++ ){
    for ( int n_y=0; n_y<y_size; n_y++ ){
      for ( int n_x=0; n_x<x_size; n_x++ ){
        const ptr_double wk42_B0 = { wk42_B0_p + n_x*1 + n_y * xdim0_opensbliblock00Kernel016*1 + n_z * xdim0_opensbliblock00Kernel016 * ydim0_opensbliblock00Kernel016*1, xdim0_opensbliblock00Kernel016, ydim0_opensbliblock00Kernel016};
        ptr_double wk9_B0 = { wk9_B0_p + n_x*1 + n_y * xdim1_opensbliblock00Kernel016*1 + n_z * xdim1_opensbliblock00Kernel016 * ydim1_opensbliblock00Kernel016*1, xdim1_opensbliblock00Kernel016, ydim1_opensbliblock00Kernel016};
        
    OPS_ACC(wk9_B0, 0,0,0) = inv_0*(-rc7*OPS_ACC(wk42_B0, 0,-1,0) + (rc7)*OPS_ACC(wk42_B0, 0,1,0) -
      rc8*OPS_ACC(wk42_B0, 0,2,0) + (rc8)*OPS_ACC(wk42_B0, 0,-2,0));


      }
    }
  }
}
