//
// auto-generated by ops.py
//
#include "./MPI_inline/rtm_common.h"


void ops_init_backend() {}

//user kernel files
#include "rtm_kernel_populate_mpiinline_kernel.cpp"
#include "fd3d_pml_kernel_mpiinline_kernel.cpp"
#include "calc_ytemp_kernel_mpiinline_kernel.cpp"
#include "calc_ytemp2_kernel_mpiinline_kernel.cpp"
#include "final_update_kernel_mpiinline_kernel.cpp"
