//
// auto-generated by ops.py
//
#define OPS_3D
#include <math.h>
#include "./MPI_inline/rtm_common.h"
//user kernel files
#include "rtm_kernel_populate_mpiinline_kernel_c.c"
#include "fd3d_pml_kernel_mpiinline_kernel_c.c"
#include "calc_ytemp_kernel_mpiinline_kernel_c.c"
#include "calc_ytemp2_kernel_mpiinline_kernel_c.c"
#include "final_update_kernel_mpiinline_kernel_c.c"
