//
// auto-generated by ops.py
//
//header
#define OPS_3D
#define OPS_API 2
#include "ops_lib_core.h"
#ifdef OPS_MPI
#include "ops_mpi_core.h"
#endif

// global constants
extern int block0np0;
extern int block0np1;
extern int block0np2;
extern double Delta0block0;
extern double Delta1block0;
extern double Delta2block0;
extern int niter;
extern double dt;
extern double gama;
extern double Minf;
extern double Re;
extern double Pr;
extern double inv_0;
extern double inv_1;
extern double inv_2;
extern double inv_3;
extern double inv_4;
extern double inv_5;
extern double rc6;
extern double rc7;
extern double rcinv8;
extern double rc9;
extern double rc10;
extern double rcinv11;
extern double rcinv12;
extern double rcinv13;
extern double rc14;

void ops_init_backend() {}

//user kernel files
#include "opensbliblock00Kernel032_cpu_kernel.cpp"
#include "opensbliblock00Kernel026_cpu_kernel.cpp"
#include "opensbliblock00Kernel027_cpu_kernel.cpp"
#include "opensbliblock00Kernel028_cpu_kernel.cpp"
#include "opensbliblock00Kernel029_cpu_kernel.cpp"
#include "opensbliblock00Kernel030_cpu_kernel.cpp"
#include "opensbliblock00Kernel031_cpu_kernel.cpp"
#include "opensbliblock00Kernel033_cpu_kernel.cpp"
#include "opensbliblock00Kernel001_cpu_kernel.cpp"
#include "opensbliblock00Kernel005_cpu_kernel.cpp"
#include "opensbliblock00Kernel009_cpu_kernel.cpp"
#include "opensbliblock00Kernel017_cpu_kernel.cpp"
#include "opensbliblock00Kernel018_cpu_kernel.cpp"
#include "opensbliblock00Kernel000_cpu_kernel.cpp"
#include "opensbliblock00Kernel002_cpu_kernel.cpp"
#include "opensbliblock00Kernel003_cpu_kernel.cpp"
#include "opensbliblock00Kernel004_cpu_kernel.cpp"
#include "opensbliblock00Kernel006_cpu_kernel.cpp"
#include "opensbliblock00Kernel007_cpu_kernel.cpp"
#include "opensbliblock00Kernel008_cpu_kernel.cpp"
#include "opensbliblock00Kernel010_cpu_kernel.cpp"
#include "opensbliblock00Kernel011_cpu_kernel.cpp"
#include "opensbliblock00Kernel024_cpu_kernel.cpp"
#include "opensbliblock00Kernel025_cpu_kernel.cpp"
#include "opensbliblock00Kernel035_cpu_kernel.cpp"
#include "opensbliblock00Kernel034_cpu_kernel.cpp"
